# config/routes.yaml

create_commande:
    path: /api/serveur/commande
    controller: App\Controller\CommandeController::createCommande
    methods: [POST]

create_boisson:
    path: /api/barman/boisson
    controller: App\Controller\BoissonController::createBoisson
    methods: [POST]

create_user:
    path: /api/patron/user
    controller: App\Controller\UserController::createUser
    methods: [POST]
