# config/packages/security.yaml

security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                always_use_default_target_path: true

            logout:
                path: app_logout
                target: app_home

            # Add remember_me config if needed
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path:     /
            #     always_remember_me: true

    access_control:
        - { path: ^/api/serveur, roles: ROLE_SERVEUR }
        - { path: ^/api/barman, roles: ROLE_BARMAN }
        - { path: ^/api/patron, roles: ROLE_PATRON }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
