security:
    # Configurer les hashers de mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Configurer les fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Configurer les firewalls de sécurité
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Utilisation des custom_authenticators pour les nouveaux authentificateurs
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                always_use_default_target_path: true

            logout:
                path: app_logout
                target: app_home

    # Configurer les contrôles d'accès
    access_control:
        - { path: ^/api/serveur, roles: ROLE_SERVEUR }
        - { path: ^/api/barman, roles: ROLE_BARMAN }
        - { path: ^/api/patron, roles: ROLE_PATRON }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }